name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Build and publish package
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
          python-version-file: "pyproject.toml"
      - name: Building package distribution
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
