name: Testing and quality control

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  code-quality:
    name: "Code QA"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run ruff linter
        run: uv run ruff check entitled
      - name: Run ruff formater
        run: uv run ruff format entitled
      - name: Run bandit
        run: uv run bandit entitled

  test:
    name: "Run test suite"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        poetry-version: [1.8.3]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest --cov=entitled --cov-report=xml tests/
